apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordineorchestrator
  labels:
    app: ordineorchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordineorchestrator
  template:
    metadata:
      labels:
        app: ordineorchestrator
    spec:
      containers:
        - name: ordineorchestrator
          image: sagacoreog/ordine-orchestrator:0.0.1
          ports:
          - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: ordineorchestrator
  labels:
    app: ordineorchestrator
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: ordineorchestrator
  type: ClusterIP