apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordiniservice
  labels:
    app: ordiniservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordiniservice
  template:
    metadata:
      labels:
        app: ordiniservice
    spec:
      containers:
        - name: ordiniservice
          image: sagacoreog/ordini-service:0.0.1
          ports:
          - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ordiniservice
  labels:
    app: ordiniservice
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: ordiniservice
  type: ClusterIP